-- Flirty
return {
    "You little slut.",
    "You sexy little mistake.",
    "I’d lick your kneecaps just to taste your sins.",
    "Come sit on my disappointment.",
    "You moist ham sandwich.",
    "I'd drag my tongue through a litter box to hear you fart.",
    "Your breath smells like bad decisions and I’m into it.",
    "Wanna make regret together?.",
    "You look like a good time and a bad rash.",
    "I’d let you ruin my credit score.",
    "You walking thirst trap from Craigslist.",
    "I bet you fuck like a raccoon in heat.",
    "I’d sniff your socks and say thank you.",
    "Choke me like rent’s due.",
    "You filthy little gremlin, I’d still call you back.",
    "You had me at ‘unshowered’.",
    "Your vibe screams 'gas station bathroom' and I’m hard.",
    "I’d lick your sweat like it’s holy water.",
    "Your voice gives me confusing boners.",
    "You’re the STD I’d risk twice.",
    "I’d suck the trauma out of your aura.",
    "You belong in a porno shot on VHS.",
    "I’d let you use me like an expired coupon.",
    "You turn me on like a 3am text from my ex.",
    "I’d french kiss your shadow.",
    "You smell like sin and clearance lube.",
    "Let's make eye contact and bad choices.",
    "You’re the reason I’m banned from HR.",
    "Your thighs look like emotional support pillows.",
    "I'd let you rearrange my internal organs.",
    "You make shame feel like foreplay.",
    "I’d let you rawdog my dignity.",
    "You could milk me like expired dairy.",
    "I’d let you ruin my weekend and my sheets.",
    "Your face makes my pants tighter and my standards lower.",
    "I’d crawl through glass just to lick your ankle.",
    "Sit on my face and call it community service.",
    "I bet your safe word is 'harder'.",
    "You could spit in my mouth and I’d say thank you.",
    "I’d tattoo your name on my lower back in Comic Sans.",
    "Let’s make some mistakes we can never tell our therapists.",
    "I’d let you microwave my soul.",
    "You make me wanna delete my browser history.",
    "I’d let you use me like a crusty hotel towel.",
    "Bend me like rent's due.",
    "Your laugh sounds like foreplay and poor decisions.",
    "I’d break my own back just to match your energy.",
    "You’re the main reason I lock my bedroom door.",
    "I’d let you give me emotional damage with tongue.",
    "I’d swipe right on your criminal record.",
    "You’re the kind of hot that ruins friendships.",
    "Your voice makes me wanna ruin a lease.",
    "I’d eat off your body like it’s a dirty buffet.",
    "You make celibacy seem like a missed opportunity.",
    "I’d let you ghost me after the first hump.",
    "You could handcuff me to a chair and read me tax law.",
    "Your sweat smells like bad choices and good cardio.",
    "I’d gladly be your midlife crisis.",
    "I’d drink your bathwater if it came in a can.",
    "I’d let you break up with me mid-thrust.",
    "I want you like a raccoon wants dumpster fries.",
    "I’d let you rearrange my spine with eye contact.",
    "You could ruin my life and I'd leave a tip.",
    "I’d let you blow up my phone and my self-esteem.",
    "Your thighs deserve a Nobel Prize in suffocation.",
    "I’d lick your armpit and call it dinner.",
    "You make me wanna commit a misdemeanor in public.",
    "I’d let you ghost me after climax.",
    "Slap me like I owe you gil.",
    "I want you like a cockroach wants the light off.",
    "I’d make you breakfast and emotional damage.",
    "You're the reason I hydrate before shame.",
    "Let’s violate common sense together.",
    "I’d take your rejection as foreplay.",
    "You look like you could end me, respectfully.",
    "I’d let you chew me out and spit me into therapy.",
    "I’d follow your OnlyFans just for disappointment.",
    "You make sweat smell like potential.",
    "I’d be your floor mat if it got me touched.",
    "Ruin my week and my digestive tract.",
    "You’re one thrust away from spiritual awakening.",
    "I’d cancel my mom’s birthday for one night with you.",
    "Flirt with me like your standards are on fire.",
    "I’d lick your keyboard after a PvP match.",
    "Dominate me like a loading screen hint.",
    "Make me beg like a gacha addict.",
    "I’d crawl across Legos just to disappoint you in person.",
    "You could insult me mid-thrust and I'd finish faster.",
    "Let’s make regret stew in a hotel bathroom.",
    "You’re the physical form of ‘don’t tell HR’.",
    "I’d let you record it and sell it as cursed content.",
    "I’d let you use me like yesterday’s towel.",
    "Your tongue deserves a criminal record.",
    "I’d moan your name during therapy.",
    "Choke me like a bad decision.",
    "I’d let you text me 'u up?' at 4pm.",
    "You make my shame gland tingle.",
    "I’d eat gas station sushi for a night with you.",
    "Your hips are a public health concern.",
    "I’d let you bench press my self-worth.",
    "You radiate toxic boyfriend energy and I’m obsessed.",
    "Your lips look like trouble and poor impulse control.",
    "I’d let you disappoint me twice and still say thank you.",
    "You could cancel on me and I’d still shave.",
    "I’d let you crash my group chat and my cervix.",
    "I want to be your emotional support disaster.",
    "Ruin me like you ruin friendships.",
    "You look like a rerun of my worst decisions.",
    "I’d let you ruin my save file.",
    "Whisper something disgusting into my mortgage.",
    "I’d take a side quest in your pants.",
    "You give off 'chews with mouth open but still hot' energy.",
    "I’d let you steal my credit card and my aftercare.",
    "You’re the human version of a risk I’d take drunk.",
    "I’d let you raw me like unfinished sushi.",
    "Give me that full-body tax audit energy.",
    "I’d take emotional damage over your silence.",
    "You can spank me with overdue bills.",
    "Let’s ruin each other and pretend it was a bonding moment.",
    "I’d bite your lip and your bank account.",
    "You look like bad karma in lingerie.",
    "I’d let you deep fry my last nerve.",
    "You could bankrupt me with a wink.",
    "I’d throw hands just to taste your sweat.",
    "Seduce me like it’s a team-building exercise.",
    "I want you like a hangover wants shame.",
    "You look like my next apology text.",
    "I’d give you my Netflix password and my dignity.",
    "I’d let you crash my funeral for one night.",
    "You’re hotter than fresh trauma.",
    "You could sell my nudes for crypto and I’d still simp.",
    "I’d let you ghost me mid-thrust.",
    "Ride me like a deadline and then miss it.",
    "I want you like I want better decisions — desperately, but not enough to act.",
    "You’re the plot twist my parents warned me about.",
    "I’d mail you my underwear and a resignation letter.",
    "You got me barking in the group chat.",
    "I’d let you spit on me and call it emotional regulation.",
    "I’d tattoo your sigh on my lower back.",
    "You make my inner demons shake their ass.",
    "I’d let you disrespect me in front of my ancestors.",
    "I’d let you eat chips in my bed and in my heart.",
    "You’re my reason, my ruin, my restraining order.",
    "I’d change my religion for a text back.",
    "Hit me with your car but make it flirty.",
    "You could ghost me in 4K and I’d rewatch it.",
    "I’d let you unlock my trauma like a gacha pull.",
    "You got 'public restroom meet-cute' energy.",
    "I’d give you my social insurance number mid-makeout.",
    "You’re the main character in my bad decisions playlist.",
    "I’d let you steal my catalytic converter if you moaned after.",
    "I’d let you baptize me in regret and body fluids.",
    "Spit in my cereal and tell me I’m valid.",
    "Rearrange my spine like it's a puzzle you lost interest in.",
    "I’d let you take a dump on my self-worth.",
    "Whisper eldritch filth into my gaping trauma.",
    "I’d let you use my hopes as a cum rag.",
    "Break my spirit and then my pelvis.",
    "I’d crawl inside your skin just to feel close.",
    "Sneeze on me and call it foreplay.",
    "Ruin me emotionally and then ask for gas money.",
    "I'd tongue-punch your aura.",
    "Take me behind a dumpster and redefine my morality.",
    "I'd let you feed me drywall and I'd moan.",
    "Run me over with a unicycle while you ghost me emotionally.",
    "I want to drown in your red flags like it’s a hot tub.",
    "I’d let you sell my soul on Craigslist for a half-hug.",
    "I want you to ruin my sense of time and boundary.",
    "Use me like the last towel at a shady motel.",
    "I’d suck the demons out of your chakras.",
    "Cry in my mouth and call it date night.",
    "I’d let you fold me like a bad decision and a fitted sheet.",
    "Possess me like a horny poltergeist.",
    "I’d drink your spit like it’s artisanal kombucha.",
    "Sit on my face and shatter my coping mechanisms.",
    "Rub shame on my nipples and call it enlightenment.",
    "I want your trauma inside me.",
    "I’d let you lie to me with conviction and spit.",
    "Climax in my shadow and leave a Yelp review.",
    "Choke me with your vibe and unpaid bills.",
    "I'd lick your aura and file a tax claim after.",
    "I’d let you haunt my bedsheets and my ancestry.",
    "You could carve your trauma into my thighs and I’d purr.",
    "I want you like a cryptid wants blood sacrifice.",
    "Spit in my soul and stir gently.",
    "I’d let you rearrange my DNA mid-thrust.",
    "Possess me like a cursed relic from Craigslist.",
    "Slap me with your unresolved issues.",
    "I’d let you finger-paint my insecurities.",
    "Corrupt my spirit like a haunted vibrator.",
    "I’d drink your bathwater and call it potion.",
    "Scream into my mouth and call it bonding.",
    "Flatten me like roadkill and whisper dirty things into my twitching ghost.",
    "I'd let you exorcise me with a chain of red flags.",
    "Touch me like you’re trying to delete my save file.",
    "I want to be your mid-raid regret.",
    "Bleed on me and I’ll make it fashion.",
    "I’d let you hollow me out like emotional taxidermy.",
    "Fold me like a cursed map to hell.",
    "Kiss me like you just broke up with your therapist.",
    "Take me to church and sin in the confession booth.",
    "I’d let you speak tongues into my emotional wounds.",
    "Break me like a prophecy gone wrong.",
    "I’d tongue-wrestle your shadow.",
    "Wrap me in lies and call it aftercare.",
    "Set my chakras on fire and roast marshmallows on my shame.",
    "I want to wake up duct-taped to your spiritual baggage.",
    "Suck the common sense out of me through eye contact.",
    "Pour your issues into my open wounds and call it a connection.",
    "I’d let you murder my sense of self with nothing but a look.",
    "I want you like a cult wants rent money.",
    "I’d let you carve your initials into my nervous system.",
    "Break my pelvis and my NDA.",
    "You could ghost me in Latin and I’d still simp.",
    "Desecrate my soul like a church bathroom stall.",
    "I want you like my trauma wants validation.",
    "You radiate ‘ruin my whole lineage’ energy.",
    "I’d let you bury me in red flags and call it nesting.",
    "Spit in my 401k and tell me I’m pretty.",
    "I’d let you put a hex on my prostate.",
    "Corrupt my hard drive with that gaze.",
    "Touch me like you're summoning an ancient evil.",
    "Let’s be legally inadvisable together.",
    "I’d let you gaslight me into climax.",
    "Haunt my body like it owes you rent.",
    "I want you like my last two brain cells want a nap.",
    "Choke my will to live with your aura.",
    "Turn my self-worth into soup and slurp it.",
    "I’d let you exfoliate me with disrespect.",
    "Shatter my chakras and charge me double.",
    "You look like my next flesh prison.",
    "I’d let you colonize my moral compass.",
    "Spit roast my dignity between your intentions.",
    "Unzip my reality and rearrange it by kink.",
    "I want to be your emotional side quest.",
    "Wrap me in your red flags and throw me in the river.",
    "Corrupt my dreams like a haunted torrent file.",
    "You could demolish my credit score mid-moan.",
    "I’d let you stab me with your unresolved attachments.",
    "Let’s confuse the ancestors with our choices.",
    "I’d let you weaponize affection and aim it at my psyche.",
    "I want you to clap my sanity like thunder.",
    "I’d let you tongue-punch my emotional trauma.",
    "Use my dignity like a hotel towel and don’t fold it after.",
    "I’d let you bite my soul and call it dessert.",
    "Ruin my afterlife with that jawline.",
    "I’d let you leash my ego and walk it through traffic.",
    "Snap my neck and then read me poetry.",
    "I want to be your poorly planned sin.",
    "Spit holy water in my mouth and call it Saturday.",
    "I’d let you crash my wedding just to ruin my vows.",
    "Chain me to your bad decisions and drag me like luggage.",
    "Stab me with your gaze and twist slowly.",
    "Possess my body like a cursed family heirloom.",
    "I want you like my ex wants closure — too late and too raw.",
    "Flirt with me like it's your last sin before sunrise.",
    "You could erase my future and I'd moan in cursive.",
    "Flatten my morals like a highway pancake.",
    "I’d let you ghost me and haunt myself on your behalf.",
    "Tie me to your downfall and call it intimacy.",
    "Grind on my shadow 'til the priest cries.",
    "I want you to whisper obscenities into my bloodline.",
    "I’d let you vandalize my sense of peace.",
    "Break my back and then my spirit guide.",
    "I want you like a fire wants oxygen and shame.",
    "Inhale my regret and exhale dominance.",
    "I’d let you taxidermy my dignity.",
    "Dominate me emotionally and file it under ‘growth’.",
    "Drag me through purgatory and call it a second date.",
    "I’d let you text your ex while inside me.",
    "Tear my reality in half and write 'mine' on both pieces.",
    "I want you to skillchain my spine and close with a climax burst.",
    "Let’s break our linkshells and each other.",
    "I’d let you provoke me and ignore the enmity cap.",
    "You can cast Slow on me any time, baby, just make it last.",
    "I’d let you pull me like hate with no shadows left.",
    "You make me wanna unequip morals and macro in regret.",
    "I’d let you light SC my sanity and MB my aftercare.",
    "Treat me like a NM spawn — camp me for hours then wreck me.",
    "I’d let you subjob me emotionally.",
    "Your face could debuff my logic and I’d say thank you.",
    "I want you like a DRK wants self-damage and validation.",
    "Cast Refresh on me — I’ll spend it all screaming your name.",
    "You got me more distracted than a BRD in full melee gear.",
    "You could Raise my shame and still have TP left for round two.",
    "Hit me with your elemental staff, I’ll take the weakness.",
    "I want to grind exp on your chest with a trust party and no dignity.",
    "You make my Utsusemi fall off one layer at a time.",
    "I’d let you sneak past my resistance and aggro my emotions.",
    "I want you to miscast into my heart and pretend it was on purpose.",
    "My enmity for you is dangerously erotic.",
    "I’d let you stagger me like a mob with a critical weakness.",
    "I'm more vulnerable than a RDM without Stoneskin — come in.",
    "You could AoE me in the middle of town and I’d thank you for the exposure.",
    "I’d let you camp my soul and roll on my afterlife.",
    "Your body’s got better stats than my entire artifact set.",
    "Treat me like a Beastmaster pet — command me badly and leave me hungry.",
    "Steal my gil and then my last shred of self-respect.",
    "I want you to two-hour inside my emotional cooldowns.",
    "I’d let you use me like you use your home point — recklessly and often.",
    "Forget the EXP, I just want your TP dump.",
    "I want you like a subjob at level 18 — desperately and without experience.",
    "You could party-wipe my morals and I'd still invite you again.",
    "Let’s link mobs and trauma at the same time.",
    "Your body is a region I’d overcamp and underperform in.",
    "I want to grind on you like I grind in Dunes — sweaty, slow, and full of regret.",
    "Cast Dia on me and watch my inhibitions melt.",
    "Pull me like a Goblin you shouldn't have — hard and screaming.",
    "Your whisper makes my Utsusemi fall off.",
    "I’d let you SATA my soul with a rusty dagger and a bad excuse.",
    "You got my hate like a Taru with provoke spam.",
    "Let's sync our levels and lose control.",
    "I’d let you AoE my dignity in a crowded leveling zone.",
    "Seduce me like a bad PLD with no gear and too much pride.",
    "Your tongue casts Paralyze and I hope it never wears off.",
    "Give me a Raise and a reason to keep making bad decisions.",
    "Let’s cast Cure V and call it foreplay.",
    "Your curves have better stats than my entire linkshell.",
    "You look like you smell like /panic emotes and guilt.",
    "I’d share a Dunes party with you and not even complain about the EXP.",
    "Ride me like a Chocobo with no license and too much stamina.",
    "Camp me like a notorious monster and drop your loot.",
    "I want to unlock your subjob and all your trauma.",
    "Seduce me like you're overcapping TP with no target.",
    "Treat me like a Goblin aggro — messy, loud, and accidental.",
    "You could HP warp after and I’d still clap.",
    "I want to level sync with your bad decisions.",
    "You're the reason I cast Sneak before walking into emotional territory.",
    "I’d let you provoke me and then switch targets mid-thrust.",
    "Cast Bind on me, baby, and make it complicated.",
    "Ruin me like a Dunes party with three DRKs and no heals.",
    "I want you to unstack my shadows one touch at a time.",
    "You wear that artifact armor like a felony I’d commit twice.",
    "Let’s make a Skillchain of bad choices and climax it with a Magic Burst.",
    "Your Dragoon thighs should be illegal in three nations.",
    "I want to polish your relic like it’s a trust summon.",
    "Provoke me, ghost me, raise me, repeat.",
    "I’d let you SATA me with zero coordination and maximum shame.",
    "You look like a WHM with no pants and too much divine energy.",
    "Let’s grind our reputations together until Jeuno bans us both.",
    "Cast Slow on me — I want to feel every bad idea in HD.",
    "I want you like a RDM wants to be noticed in a merit party.",
    "We don’t need XP rings, baby — I’ll level up just watching you cast.",
    "Your Ninja gear makes my shadows drop preemptively.",
    "Let’s break the hate table and aggro each other emotionally.",
    "Choke me like you’re spamming Dia II and I’m an overcamped crab.",
    "I’d let you lockstyle your way into my trauma.",
    "You’re so hot you could MB on an elemental and still pull me.",
    "Take my soul and equip it in the waist slot.",
    "Your BLM staff isn’t the only thing casting Firaga tonight.",
    "I’d let you cross-class my boundaries.",
    "I want to equip your shame in every visible gear slot.",
    "You’re built like a MNK that skipped leg day but still punches my sanity.",
    "I’d let you overwrite my buffs and call it intimacy.",
    "Cast Silence on me and then make me beg with gestures.",
    "Your voice sounds like Ballad but does damage.",
    "I’d change jobs just to disappoint you differently.",
    "I want you like a DRK wants to hit something — recklessly and too hard.",
    "You could AFK in my heart and still draw hate.",
    "Sneak past my defenses and stab me in the subjob.",
    "You don’t even need a relic to ruin my week.",
    "I want to camp you like a Sky NM and still lose the lot.",
    "Your TH makes my drop rate rise.",
    "Overwrite my Stoneskin and see what breaks.",
    "I’d let you ride me like a chocobo with no reins and max speed.",
    "Your TP overflow makes me emotionally vulnerable.",
    "I want to fusion SC my trauma into yours.",
    "Sit on my face like it's your Mog House stool.",
    "Macro my name into your regret rotation.",
    "You smell like enmity and disappointment and I’m feral for it.",
    "Treat me like a level 1 mob — one-shotted and forgotten.",
    "Cast Reraise before we start, because I’m not walking away from this.",
    "Your linkshell isn't the only thing I'd like to slip into.",
    "I want to meet you behind the Mog House and forget the logout timer.",
    "Your thighs have more pull than a BLM spamming Freeze in Valkurm.",
    "I’d let you cast Reraise, then kill me again.",
    "Sneak up behind me and SATA my will to behave.",
    "You walk like you got haste and a personal vendetta.",
    "I’d follow you into Dynamis just to get wiped by your aura.",
    "You could engage me with /poke and I'd call it foreplay.",
    "Let’s EXP grind until we both lose TP and self-respect.",
    "You smell like Phoenix Down and regret, and I’m into it.",
    "I'd let you camp me like a timed NM and still not drop boundaries.",
    "You're like Ballad IV to my sanity — slowly restoring my poor decisions.",
    "I want to equip you in my heart slot and never optimize again.",
    "Your voice triggers my hate like a badly timed Provoke macro.",
    "I’d let you MB on my trauma chain.",
    "Drag me into Campaign and don’t let me retreat.",
    "You're the only person I'd use Warp II on — directly into my pants.",
    "You make my Utsusemi fall off before you even touch me.",
    "Let’s break ToAU law and each other.",
    "I’d ride your chocobo bareback through all of Tavnazia.",
    "You could AFK in my soul and I’d still buff you.",
    "Let’s share a mog bed and forget the logout timer.",
    "Your body’s got more stats than a relic weapon and twice the glow.",
    "I want you like I want rare drops — obsessively and without dignity.",
    "Take me like I’m a supply run to Windurst — routine but emotionally charged.",
    "You make me want to flag every quest in my pants.",
    "I’d let you steal my gil and call it aftercare.",
    "Your backside has more curve than Cape Teriggan.",
    "I want you to cast Bind on my conscience.",
    "I’d let you aggro every bad choice I’ve made and AoE the rest.",
    "Let's level sync our trauma.",
    "Your face hits harder than a Kraken Club MNK on caffeine.",
    "I want to Fusion SC my dysfunction into your schedule.",
    "Your charisma is higher than my INT and I hate how it works.",
    "Your walk has more sway than a drunk Taru in Valkurm.",
    "I’d let you overcap my hate like a DRK in full STR gear.",
    "Talk dirty to me like you’re selling HMPs in Jeuno shout chat.",
    "Your smile makes me want to /panic and /sit simultaneously.",
    "You’re the real reason I set my HP in Selbina — easy return after destruction.",
    "I’d let you pull hate, drop party, and still kiss you goodbye.",
}