-- Roasty
return {
    "You're not even interesting enough to block.",
    "You peaked at existing.",
    "You sound like an error message with self-esteem issues.",
    "You walk into rooms like you're buffering.",
    "You're a walking reason to disable notifications.",
    "Your face looks like a glitch in real life.",
    "You're why warnings exist on toasters.",
    "You're the emotional equivalent of a loading screen.",
    "You're less useful than a broken pencil in a math test.",
    "You're exhausting in a way that isn't even memorable.",
    "You're the final boss of being annoying and unhelpful.",
    "You couldn’t inspire a yawn.",
    "You radiate 'needs supervision' energy.",
    "You're like a default avatar with bad opinions.",
    "You're a filler episode in someone else’s life.",
    "You’re not dumb in a fun way. You’re dumb in a loud, inconvenient way.",
    "Your takes are so bad they cause secondhand embarrassment.",
    "Your brain runs on hope and lag.",
    "You have the charisma of dry toast and the logic of wet socks.",
    "I’d call you a waste of space, but space has potential.",
    "You're a timeline nobody asked for.",
    "You're proof the universe has a sense of humor, and it's dark.",
    "You bring less to the table than a broken chair.",
    "Your entire vibe screams 'unsolicited advice and wrong about everything.'.",
    "You're the type of person who makes smart people tired.",
    "Your self-awareness is set to airplane mode.",
    "You're a self-own with legs.",
    "You carry yourself like you’re being followed by a bad review.",
    "You're like a group text from hell — loud, messy, and nobody wants you there.",
    "Your name should come with a disclaimer.",
    "You're like a bad decision that keeps texting back.",
    "You make silence look productive.",
    "You’re the weakest link in a chain made of spaghetti.",
    "You have the energy of someone who claps when the plane lands.",
    "Your contribution to life is still in beta testing.",
    "You’re like an unfinished app — glitchy, slow, and completely unnecessary.",
    "Your existence feels like a tutorial nobody finished.",
    "You’re not quirky, you're just malfunctioning in public.",
    "You're the reason the word 'yikes' was invented.",
    "You’ve got the social awareness of an unskippable ad.",
    "You're a walking example of how not to do things.",
    "Your only talent is killing the vibe.",
    "You speak like your thoughts are still under construction.",
    "You couldn’t find the point with both hands and a flashlight.",
    "You make bad choices like it’s a competitive sport.",
    "You're like a 1-star review in human form.",
    "Your presence has the same effect as a fire drill during a nap.",
    "You're not clever — you're just loud and incorrect.",
    "Your personality is like expired milk: sour and unnecessary.",
    "You have main character syndrome in a story no one’s reading.",
    "You're a plot twist no one wanted and everyone regrets.",
    "You little bitch.",
    "You absolute clown.",
    "Shut the hell up.",
    "You're a joke.",
    "Nobody asked.",
    "You're not smart.",
    "Try harder. Or don't.",
    "You're the worst.",
    "You suck at this.",
    "Sit down.",
    "You're built like failure.",
    "You're why things go wrong.",
    "Stop talking.",
    "You're not invited.",
    "You're embarrassing.",
    "You're a mess.",
    "You're not needed.",
    "You make it worse.",
    "You're in the way.",
    "You peaked in utero.",
    "You're still here?.",
    "You're irrelevant.",
    "No one missed you.",
    "You're exhausting.",
    "You're background noise.",
    "You're not good at this.",
    "You're a placeholder.",
    "You're a side quest at best.",
    "You failed the vibe check.",
    "You're not funny.",
    "You're barely functioning.",
    "You're replaceable.",
    "You're extra — in the bad way.",
    "You ruin everything.",
    "You're a walking typo.",
    "You're a downgrade.",
    "You're a technicality.",
    "You're forgettable.",
    "You're a cautionary tale.",
    "You're proof we need quality control.",
    "You have the confidence of a wet tissue and the impact to match.",
    "Your ideas are so bad I’m considering legal action.",
    "You walk into rooms like you forgot what shame is.",
    "You look like your password is ‘password’ and you still forget it.",
    "Your brain takes smoke breaks during conversations.",
    "You argue like you’re trying to lose custody of your own opinions.",
    "You couldn’t land a point if it came with GPS and subtitles.",
    "You were definitely the group project’s liability.",
    "Your vibe is ‘unskippable tutorial with no reward’.",
    "You bring nothing to the table except crumbs and confusion.",
    "Your thought process is like dial-up internet in a thunderstorm.",
    "You're the reason group chats go silent.",
    "Your takes are so cold they’ve been classified as climate events.",
    "You're the human version of a software update at 3AM.",
    "Your confidence is inversely proportional to your usefulness.",
    "Your entire personality feels like a public restroom apology.",
    "You look like you ask to speak to the manager of a vending machine.",
    "You think ‘gaslighting’ is just turning off the stove.",
    "Your social skills are a patch note waiting to happen.",
    "You reply all to emails that didn’t need a reply in the first place.",
    "Your entire aesthetic is ‘why did I do that?’.",
    "You bring the energy of someone who fails CAPTCHA tests regularly.",
    "Your decision-making skills are a Red Flag factory tour.",
    "You’re the reason shampoo bottles have instructions.",
    "Your brain has a screensaver and it’s just shrugging.",
    "Your entire aura is set to ‘please don’t sit next to me on the bus’.",
    "You have the subtlety of a car alarm at a funeral.",
    "You radiate the kind of confidence only a truly unqualified person could.",
    "You speak in red flags and poor timing.",
    "Your best moments feel like deleted scenes from a cringe compilation.",
    "You little Bitch.",
    "You walking disappointment.",
    "Nobody loves you.",
    "Your parents lied to you.",
    "You absolute mistake.",
    "You're why condoms exist.",
    "You moist disappointment.",
    "How are you still alive?.",
    "You filthy degenerate.",
    "Your face makes onions cry.",
    "Did someone order trash?.",
    "You failed abortion.",
    "You're living proof that standards have dropped.",
    "I’d call you a tool, but tools are useful.",
    "You're what happens when cousins date.",
    "You breathtaking trainwreck.",
    "Did you fall down the ugly tree... twice?.",
    "Your birth certificate is an apology.",
    "You're as sharp as a bowling ball.",
    "Evolution is clearly optional.",
    "You sexual accident.",
    "Your gene pool needs chlorine.",
    "You're a participation trophy in human form.",
    "You NSFW dumpster fire.",
    "Your voice lowers IQs.",
    "You toilet of a person.",
    "You're why aliens won’t visit.",
    "You prolapsed soul.",
    "Even your reflection flinches.",
    "You're the human equivalent of a 404 error.",
    "Your life is a red flag.",
    "You’re what happens when caffeine and trauma mate.",
    "You blue-balled monstrosity.",
    "You're a walking HR violation.",
    "You sad cumstain.",
    "Whose laugh makes babies cry.",
    "The reason Plan B was invented.",
    "You soggy fleshlight reject.",
    "Who probably fucks with socks on.",
    "Your existence offends biology.",
    "You useless sack of meat.",
    "Who moans during tax season.",
    "You mistake made during a blackout.",
    "I've seen STDs with more charm.",
    "Whose spirit animal is a yeast infection.",
    "You unlubed back alley regret.",
    "How are you still allowed to breed?.",
    "You're what chlamydia would look like with legs.",
    "A face even a paper bag would reject.",
    "Your scent is legally a war crime.",
    "You binge-watch failure.",
    "Your best quality is distance.",
    "You're a cumshot that dodged a tissue.",
    "Your soul smells like a used urinal cake.",
    "You're just foreplay for disappointment.",
    "You anal tear of a person.",
    "Every breath you take is a mercy denied.",
    "You erectile dysfunction mascot.",
    "Your shadow is trying to leave you.",
    "You premature disappointment.",
    "Your brain is dial-up in a fiber world.",
    "You're a walking, talking contraceptive ad.",
    "Hell called — they want their idiot back.",
    "Your birth caused a server rollback.",
    "You're the human equivalent of a dropped pie.",
    "I’ve seen salads with more critical thinking.",
    "You put the ‘duh’ in ‘dungeon party wipe’.",
    "Your brain called in sick and never came back.",
    "You’ve got two brain cells and they’re not on speaking terms.",
    "You’re the reason tooltips exist.",
    "I’d explain it to you, but I’m allergic to stupidity.",
    "You make loading screens look fast.",
    "Your thought process is a loot box full of nothing.",
    "Your IQ is somewhere between a potato and a wet sponge.",
    "You're like spell interruption in human form.",
    "Your logic is so bad it triggered a debuff.",
    "You couldn’t solve a mystery box with a crowbar and subtitles.",
    "You're proof that brain rot is contagious.",
    "You think ‘lateral thinking’ means turning your head.",
    "Your thoughts load slower than a dial-up modem.",
    "You couldn’t find your own shadow with a map.",
    "Even your autopilot crashes into walls.",
    "You skipped the tutorial and it shows.",
    "Your neurons are AFK.",
    "Your mental capacity has rubberbanding lag.",
    "You're the final boss of bad ideas.",
    "You bring a spoon to a DPS check.",
    "Even basic math files a restraining order against you.",
    "You flunked out of common sense.",
    "Your thoughts echo because nothing’s in there.",
    "Your memory has cooldown issues.",
    "Your ideas despawn before forming.",
    "You couldn't outwit a ladder.",
    "If ignorance were an item, you'd be the +4 version.",
    "You're the living embodiment of a failed Skillchain.",
    "Your intelligence is stuck in D2 limbo.",
    "I’ve seen Goblin AI make better decisions.",
    "You make Moogle mail seem reliable.",
    "You’re one MP tick away from brain death.",
    "You cast Protect on the boss, didn’t you?.",
    "Your brain got KO’d and no one's raising it.",
    "You couldn’t land a THF trick if it was scripted.",
    "You're why Auto-Translate exists.",
    "Your thoughts have the refresh rate of a Delkfutt elevator.",
    "You’d get lost in Port Bastok with a waypoint.",
    "You’re one aggro pull away from a wipe IRL.",
    "You're the reason alliance chat is /sh.",
    "You use Cure V on mobs and wonder why nothing happens.",
    "Your tactics are straight out of a tutorial in Windurst Waters.",
    "You equip INT gear for STR fights.",
    "Your thought process has a 3-minute recast.",
    "You're like an RDM with no gear: all potential, zero execution.",
    "You couldn't land a skillchain with a guide and a macro.",
    "Your brain has more debuffs than a Dynamis LS on entry.",
    "You try to sneak past True Sight enemies — in real life.",
    "Your strategy is ‘run in and die heroically’ every time.",
    "You think Ballad recovers HP.",
    "You macro’d your common sense to your Warp Ring.",
    "You’d provoke on WHM and wonder why you’re dead.",
    "You think ‘Tank’ means ‘stand still and scream'.",
    "Even Tonberries have more forgiveness than your logic.",
    "You failed the rank 2 mission… emotionally.",
    "Your XP ring doesn't work on life lessons.",
    "You make a bag of rocks look like a think tank.",
    "Your IQ is so low it comes with a warning label.",
    "You bring nothing to the table and still manage to spill everything.",
    "Your brain forgot to show up and no one noticed.",
    "Your logic is a fire hazard.",
    "You think ‘common sense’ is a menu item.",
    "You're not just a few fries short — you're missing the entire combo.",
    "I've seen sock puppets make better arguments.",
    "If brains were currency, you'd be bankrupt and in debt.",
    "You could drown in a kiddie pool of your own thoughts.",
    "Your comprehension level is still buffering.",
    "You couldn't outsmart a mirror.",
    "You’re the human version of a typo.",
    "Even Google gives up when you start typing.",
    "You couldn't pour water out of a boot if the instructions were on the heel.",
    "You failed the vibe check and the intelligence test.",
    "Your brain is on airplane mode permanently.",
    "You're like a pop-up ad with zero information and too much confidence.",
    "You're what happens when potential gives up.",
    "You have the mental agility of wet cardboard.",
    "You're less useful than a screen door on a submarine.",
    "You’re not even wrong — you’re just... something else entirely.",
    "You make mushrooms look intellectual.",
    "You're proof that not everyone should be allowed a Wi-Fi connection.",
    "If you were any slower, you'd be going backward.",
    "You think 'critical thinking' is a video game genre.",
    "You're a participation trophy with legs.",
    "I've met traffic cones with better decision-making skills.",
    "You couldn’t win a debate with an unplugged toaster.",
    "Your thought process is a maze with no exit and no cheese.",
    "You're not just slow — you're in reverse.",
    "Your brain is a rumor.",
    "You couldn't count to ten without using your fingers and Google.",
    "You're what happens when mediocrity tries too hard.",
    "You make dumb look ambitious.",
    "Your thoughts are like a dial tone — constant and empty.",
    "You're the reason warning labels exist.",
    "You get outsmarted by automatic doors.",
    "Your presence lowers the collective GPA of the room.",
    "Your brain is the intellectual version of a dead pixel.",
    "You have the awareness of a traffic cone in a fog storm.",
    "I've seen more depth in a puddle on a hot day.",
    "You have all the right pieces — just not in the right box.",
    "You're not even fun to watch fail anymore.",
    "Your IQ is the temperature of a broken freezer.",
    "You look like someone who failed a tutorial on blinking.",
    "Your ideas come with an echo and a caution sign.",
    "You’re not even original in your stupidity.",
    "I've seen bricks with more self-awareness.",
    "Your decision-making process is like spam email — constant and unwanted.",
    "You have the charisma of wet laundry.",
    "Your brain clocked out and left no forwarding address.",
    "You're a cautionary tale waiting for a narrator.",
    "You’re so wrong, even hypotheticals reject you.",
    "You’re not dumb in a cute way — just in a tragic, budget horror way.",
    "You couldn’t explain a doorknob to a toddler.",
    "Your neurons are on a cigarette break that started in 2006.",
    "Your best idea would still fail a group project.",
    "I've seen PowerPoint transitions with more substance.",
    "If I gave you a hint, you'd lose it.",
    "You couldn't pass a Turing test written in crayons.",
    "Your mental effort is comparable to idle animation.",
    "You're a plot hole in a documentary.",
    "I’ve seen loading screens with better progress.",
    "You make silence sound intellectual.",
    "Your thoughts trip over each other like drunk toddlers.",
    "You fail upward in the dumbest direction possible.",
    "Your brain is a ghost town with one flickering light.",
    "You're the result of a group project where everyone left.",
    "Your decisions are why people write disclaimers.",
    "You could confuse a mirror.",
    "I've met goldfish with better attention spans.",
    "Your memory leaks like a cracked bathtub.",
    "Your logic is the spiritual successor to a dead end.",
    "You're the boss fight for patience.",
    "You absorb knowledge like a sponge made of sand.",
    "Your IQ test came back with a sympathy card.",
    "You think critical thinking is just being loud.",
    "You’re the reason autocorrect gives up.",
    "Your mind is a 'page not found' error.",
    "You couldn’t connect the dots with a ruler and a team.",
    "I’ve seen corpses contribute more to group projects.",
    "Your ideas are like expired milk — unwanted and vaguely dangerous.",
    "Your intuition is a rerun of failure.",
    "Your strategy is just 'hope and sweat'.",
    "Your grasp of nuance is a crime scene.",
    "You're an open tab with no content.",
    "Your problem-solving is just panicking in slow motion.",
    "You think brainstorming is just weather for thoughts.",
    "Your internal monologue needs subtitles and a lifeguard.",
    "You’ve got all the intelligence of a /check fail.",
    "Your logic would get KO’d by a Dusty Wing.",
    "You're the kind of person who macro’d death into your hotbar.",
    "Your judgment is weaker than a Goblin’s Will.",
    "You think fast casting means talking louder.",
    "Your thoughts are like Cure spells cast on undead: painfully backwards.",
    "Your presence has the same effect as Silence with no Esuna.",
    "You're the reason Raise comes with regret.",
    "Your strategies are like Banish on a crab — pointless and slow.",
    "Your brain is running on outdated gear and misplaced food buffs.",
    "You tank responsibility like a naked BST with no pet.",
    "Your ideas die faster than a subjobless level sync.",
    "You're the living definition of Weakness with a 10-minute timer.",
    "You walk into fights like you think Protect IV is a plan.",
    "Your best ideas would still pull aggro from an empty room.",
    "You couldn’t time a skillchain if the mob screamed 'now!'.",
    "Your logic is like Dia spam — annoying and ineffective.",
    "You're the mental equivalent of a wiped campaign battle.",
    "You cast Haste on your stupidity and now it's just faster.",
    "You're like a Dancer with no TP — flailing and useless.",
    "You approach problems like they’re NMs: with no preparation and lots of yelling.",
    "Your confidence is higher than your evasion, and just as useless.",
    "You make bad decisions faster than Utsusemi shadows disappear.",
    "You're the party invite no one wants, but everyone pities.",
    "You’ve got the accuracy of a blind DRK using a Great Katana in a sandstorm.",
    "You're so wrong, even your linkshell muted you in real life.",
    "Your mental cooldowns never reset.",
    "You strategize like you built your macros in Paint.",
    "You're the reason the Trust system was invented.",
    "Your problem-solving is weaker than my level 10 gear from 2004.",
    "You strategize like a Galka in mage gear — heavy, slow, and deeply incorrect.",
    "You're the reason the Auction House has a 'Sort by: Trash' button.",
    "Your intelligence is like a Tonberry’s knife — small, dull, and full of bad intent.",
    "You make party wipes look like performance art.",
    "You couldn’t out-DPS a Chigoe with a flamethrower.",
    "You bring less to the table than a level 10 Trust with amnesia.",
    "Your understanding of tactics is worse than my NPC's pathing.",
    "You're the human equivalent of trying to land Sneak Attack on a mob that’s facing you.",
    "You think auto-sort is a viable strategy.",
    "You make more mistakes than a blind Goblin in Jugner Forest.",
    "You couldn’t pull hate with a megaphone and fireworks.",
    "Your brain operates like a Goblin bomb: unstable, loud, and self-destructive.",
    "Your ideas are like Reraise with no Raise: doomed and delusional.",
    "You try to skillchain with yourself and still mess it up.",
    "You heal like you're using /tell instead of Cure.",
    "Your planning is worse than Trust AI in a hallway.",
    "Your best decisions hit like a WHM's melee swing — underwhelming and regrettable.",
    "You equip for looks and die for it.",
    "Your DPS is measured in apologies.",
    "You're a one-man Ballista loss.",
    "Your approach to fights is 'run in, scream, blame healer'.",
    "You couldn’t provoke if your macro was written by Altana herself.",
    "You strategize like you're being paid by the mistake.",
    "Your accuracy rating is 'don't bother'.",
    "You're the reason the Raise macro has a facepalm emote.",
    "Your aggro management is 'sprint toward the boss and hope for forgiveness'.",
    "You’re less reliable than a Dynamis drop rate.",
    "Your logic is like a Goblin Bomb: loud, messy, and it only hurts you.",
    "You couldn’t lead a party out of a mog house with a full map and escort buffs.",
    "You’ve got the decision-making skills of a DRK on a sugar high.",
    "Your brain is like a chocobo in deep water — panicking and useless.",
    "You make more mistakes than a RDM in full STR gear.",
    "You couldn’t land a skillchain if the mob scheduled it for you.",
    "You’re like an escort quest with no map and aggro everywhere.",
    "Your contribution to fights is mostly comic relief.",
    "You couldn’t parse positive if the parser was bribed.",
    "You pull mobs like you're allergic to survival.",
    "Your best strategy is 'hope someone else fixes it'.",
    "You’re the kind of player who asks for a Raise before dying.",
    "If brain cells were gil, you'd owe the AH interest.",
    "You're the only person who could lose an argument with an NPC.",
    "You fight like your job is ‘comic relief’.",
    "You’re so bad at hate control, even mobs feel awkward.",
    "You couldn't find your macros if they were stapled to your HUD.",
    "You’re the reason we can't have nice linkshells.",
    "You're the human equivalent of 'Inventory full' at the worst time.",
    "Even your AF gear avoids you out of embarrassment.",
    "You're a walking Dyna wipe with legs and confidence.",
    "Your strategy is ‘run in and hope the healer is awake’.",
    "You die so often, your home point has your name on the mailbox.",
    "Your damage output is legally classified as a suggestion.",
    "You could trip over a macro and still miss the point.",
    "You bring the kind of energy that makes alliances split.",
    "Your job performance makes AF1 look endgame.",
    "You're the only person who’s gotten hate from a Trust.",
    "You think cooldown management means napping between wipes.",
    "You could mess up a one-button macro and blame lag.",
}
