--[[
Wardrobe9 - Windower addon for Final Fantasy XI
BSD 3-Clause License

Copyright (c) 2026 Broguypal
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain this notice.
2. Redistributions in binary form must reproduce this notice in documentation.
3. Neither the name of the author nor contributors may be used to endorse or
   promote products derived from this software without prior written permission.

THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
]]

return function(res, extdata, util, slots, ADDON_PATH, SCAN_FILE)
    local M = {}

    local function decode_augstr(entry)
        local augstr = ''
        if not entry or not entry.extdata then return augstr end
        local ok, decoded = pcall(extdata.decode, entry)
        if ok and decoded then
            local a = nil
            if type(decoded.augments) == 'table' then
                a = decoded.augments
            elseif type(decoded.augment) == 'table' then
                a = decoded.augment
            end
            if type(a) == 'table' then
                -- Normalize to a stable, sorted ';' separated string.
                augstr = util.normalize_aug_list(a)
            end
        end
        return augstr
    end

    function M.scan_all_bags_to_cache()
        util.ensure_dir(ADDON_PATH)

        local f, e = io.open(SCAN_FILE, 'w')
        if not f then return false, ('Failed to write scan cache: %s'):format(tostring(e)) end

        f:write('-- Auto-generated by Wardrobe9 scan. Edit if you want.\n')
        f:write(('return { generated_at=%d, items={\n'):format(os.time()))

        local bag_ids = {}
        for id,_ in pairs(res.bags) do bag_ids[#bag_ids+1] = id end
        table.sort(bag_ids)

        local total = 0
        for _,bag_id in ipairs(bag_ids) do
            local bag = res.bags[bag_id]
            local bag_name = bag and bag.en or ('Bag '..tostring(bag_id))
            local contents = windower.ffxi.get_items(bag_id)

            if contents and contents.max and contents.max > 0 then
                for slot=1,contents.max do
                    local entry = contents[slot]
                    if entry and entry.id and entry.id ~= 0 then
                        local r = res.items[entry.id]
                        local name = r and r.en or nil
                        if name then
                            name = util.trim(name)
                            local augstr = decode_augstr(entry)

                            local group = nil
                            local fmask = nil

                            if type(entry.flags2) == 'number' then
                                fmask = entry.flags2
                            elseif type(entry.flags) == 'number' then
                                fmask = entry.flags
                            end

                            if type(fmask) == 'number' then
                                local function has(slotname)
                                    local m = slots.FALLBACK_MASK[slotname]
                                    if not m then return false end
                                    local r2 = slots.band(fmask, m)
                                    return r2 ~= nil and r2 ~= 0
                                end

                                if has('head') then group = 'head'
                                elseif has('body') then group = 'body'
                                elseif has('hands') then group = 'hands'
                                elseif has('legs') then group = 'legs'
                                elseif has('feet') then group = 'feet'
                                elseif has('neck') then group = 'neck'
                                elseif has('waist') then group = 'waist'
                                elseif has('back') then group = 'back'
                                elseif has('left_ear') or has('right_ear') then group = 'ear'
                                elseif has('left_ring') or has('right_ring') then group = 'ring'
                                elseif has('ammo') then group = 'ammo'
                                elseif has('main') or has('sub') or has('range') then group = 'weapon'
                                end
                            end

                            if not group or group == '' then
                                group = slots.infer_group_for_item_id(entry.id)
                            end

                                                        local safe_name = util.lua_quote(name)
                                                        local safe_aug  = util.lua_quote(augstr)
                                                        local safe_bag  = util.lua_quote(bag_name)

                            local key = name
                            if augstr ~= '' then key = name .. '|' .. augstr end
                                                        local safe_key  = util.lua_quote(key)

                            -- NOTE: key is included so planner/executor can be augment-strict.
                            f:write(('  {bag_id=%d, bag_name="%s", slot=%d, item_id=%d, name="%s", aug="%s", key="%s", group="%s"},\n')
                                :format(bag_id, safe_bag, slot, entry.id, safe_name, safe_aug, safe_key, tostring(group or '')))
                            total = total + 1
                        end
                    end
                end
            end
        end

        f:write('}}\n')
        f:close()

        return true, ('Scan complete: wrote %d items to %s'):format(total, SCAN_FILE)
    end

    function M.load_scan_cache()
        local ok, t = pcall(dofile, SCAN_FILE)
        if not ok or type(t) ~= 'table' or type(t.items) ~= 'table' then
            return nil, 'Scan cache not found or invalid. In the Mog House UI, press SCAN.'
        end
        return t, nil
    end

    return M
end
